version: '3'

services:
  vue-app:
    build: ./frontend
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
  backend:
    build: ./server
    ports:
      - 8000:8000
      - 9229:9229 # debugger port 
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/db_postgres
      PORT: 8000
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_postgres
      POSTGRES_HOST_AUTH_METHOD: trust